#! .venv/bin/python

import sys

import pytest


def main(arg: str) -> None:
    if arg.endswith(".py"):
        dir, file = arg.split("/")
    else:
        dir = arg[:-1] if arg.endswith("/") else arg
        file = "_".join(dir.split("-")) + "_test.py"
    pytest.main(["-o", "markers=task", f"{dir}/{file}"])


if __name__ == "__main__":
    assert len(sys.argv) == 2, sys.argv
    main(sys.argv[1])
