#! .venv/bin/python

import subprocess
import sys


def main(arg: str) -> None:
    if arg.endswith(".py"):
        dir, file = arg.split("/")
    else:
        dir = arg[:-1] if arg.endswith("/") else arg
        file = "_".join(dir.split("-")) + "_test.py"
    subprocess.run(f"python {dir}/{file}", shell=True)


if __name__ == "__main__":
    assert len(sys.argv) == 2
    main(sys.argv[1])
